# Generated by Django 3.2.14 on 2023-07-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_walletpass', '0009_auto_20230709_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='push_token',
            field=models.CharField(max_length=255),
        ),
    ]
