# Generated by Django 6.0.4 on 2026-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_walletpass', '0010_alter_registration_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='push_token',
            field=models.TextField(),
        ),
    ]
